TABLE_EDGE_GRAB_PX     = 4
TABLE_SCROLL_MARGIN_PX = 24
TABLE_SCROLL_INTERVAL_MS = 120

PREVIEW_WIDTH  = 1500
PREVIEW_HEIGHT = 750
PREVIEW_UNDO_LIMIT = 50

MAIN_WINDOW_MIN_WIDTH  = 760
MAIN_WINDOW_MIN_HEIGHT = 580
